/**
 * Record ids, generated by the app before a row is written.
 *
 * Time-ordered prefix so ids sort chronologically, which makes a raw table dump
 * readable and gives SQLite better index locality than a purely random key.
 * The random suffix is what makes a collision implausible; the app is
 * single-device, so this does not need to be a full UUID.
 */
export function newId(): string {
  const time = Date.now().toString(36).padStart(9, '0');
  const random = Math.random().toString(36).slice(2, 10);
  return `${time}${random}`;
}
