/**
 * SCHEMA — SQLite via Drizzle.
 *
 * Conventions, applied without exception:
 *   · Money is INTEGER cents. There is no REAL column anywhere in this file.
 *   · Business dates are TEXT 'YYYY-MM-DD' in local time.
 *   · Audit timestamps are TEXT ISO-8601 UTC.
 *   · Ids are generated by the app before the row is written.
 *   · Every table carries created_at / updated_at / deleted_at. Nothing is ever
 *     hard-deleted: deleting a sold vehicle would erase a closed deal, its cost
 *     basis, and a settled split with Fernando.
 *
 * Column names are snake_case; the domain layer uses camelCase. The mapping
 * lives only in db/mappers.ts, so renaming a column touches one file.
 */

import { sql } from 'drizzle-orm';
import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const auditColumns = {
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
};

export const vehicles = sqliteTable(
  'vehicles',
  {
    id: text('id').primaryKey(),
    year: integer('year'),
    make: text('make').notNull().default(''),
    model: text('model').notNull().default(''),
    trim: text('trim').notNull().default(''),
    vin: text('vin').notNull().default(''),
    mileageIn: integer('mileage_in'),
    mileageOut: integer('mileage_out'),
    purchaseDate: text('purchase_date').notNull(),
    saleDate: text('sale_date'),
    type: text('type').notNull(),
    status: text('status').notNull().default('PURCHASED'),
    estimatedSalePriceCents: integer('estimated_sale_price_cents'),
    notes: text('notes').notNull().default(''),
    ...auditColumns,
  },
  (t) => [
    index('idx_vehicles_status').on(t.status),
    index('idx_vehicles_type').on(t.type),
    index('idx_vehicles_purchase_date').on(t.purchaseDate),
    // Deliberately NOT unique. Buying back a car you previously sold is a real
    // second deal with the same VIN, and a unique index would break the app the
    // day it happens. Duplicates are surfaced as a warning in the UI instead.
    index('idx_vehicles_vin').on(t.vin),
  ],
);

export const expenses = sqliteTable(
  'expenses',
  {
    id: text('id').primaryKey(),
    vehicleId: text('vehicle_id')
      .notNull()
      .references(() => vehicles.id),
    categoryId: text('category_id').notNull(),
    amountCents: integer('amount_cents').notNull(),
    date: text('date').notNull(),
    description: text('description').notNull().default(''),
    paidBy: text('paid_by').notNull().default('DANIEL'),
    /** 1 when the cost came out of Inventory, so the cash model skips it. */
    fromInventory: integer('from_inventory', { mode: 'boolean' }).notNull().default(false),
    inventoryItemId: text('inventory_item_id'),
    ...auditColumns,
  },
  (t) => [
    index('idx_expenses_vehicle').on(t.vehicleId),
    index('idx_expenses_category').on(t.categoryId),
    index('idx_expenses_date').on(t.date),
  ],
);

export const sales = sqliteTable(
  'sales',
  {
    id: text('id').primaryKey(),
    vehicleId: text('vehicle_id')
      .notNull()
      .references(() => vehicles.id),
    saleDate: text('sale_date').notNull(),
    salePriceCents: integer('sale_price_cents').notNull(),
    buyerName: text('buyer_name').notNull().default(''),
    notes: text('notes').notNull().default(''),
    danielShareCents: integer('daniel_share_cents').notNull(),
    fernandoShareCents: integer('fernando_share_cents').notNull().default(0),
    reinvestCents: integer('reinvest_cents').notNull().default(0),
    distributeCents: integer('distribute_cents').notNull().default(0),
    ...auditColumns,
  },
  (t) => [
    // One LIVE sale per vehicle. A reversed sale is soft-deleted and the car
    // can be sold again; two active sales for one car is not representable.
    uniqueIndex('uq_sales_active_vehicle')
      .on(t.vehicleId)
      .where(sql`deleted_at IS NULL`),
    index('idx_sales_date').on(t.saleDate),
  ],
);

export const capitalEvents = sqliteTable(
  'capital_events',
  {
    id: text('id').primaryKey(),
    kind: text('kind').notNull(),
    amountCents: integer('amount_cents').notNull(),
    date: text('date').notNull(),
    notes: text('notes').notNull().default(''),
    ...auditColumns,
  },
  (t) => [index('idx_capital_date').on(t.date)],
);

export const distributions = sqliteTable(
  'distributions',
  {
    id: text('id').primaryKey(),
    amountCents: integer('amount_cents').notNull(),
    date: text('date').notNull(),
    vehicleId: text('vehicle_id').references(() => vehicles.id),
    reason: text('reason').notNull().default(''),
    ...auditColumns,
  },
  (t) => [index('idx_distributions_date').on(t.date)],
);

export const fernandoEntries = sqliteTable(
  'fernando_entries',
  {
    id: text('id').primaryKey(),
    kind: text('kind').notNull(),
    amountCents: integer('amount_cents').notNull(),
    date: text('date').notNull(),
    sourceId: text('source_id'),
    vehicleId: text('vehicle_id').references(() => vehicles.id),
    notes: text('notes').notNull().default(''),
    ...auditColumns,
  },
  (t) => [
    /**
     * THE double-counting guarantee, enforced by the database.
     *
     * An expense Fernando paid can produce exactly one reimbursement, and a
     * sale exactly one profit share. A double-tapped save button, a retried
     * write, or a future bug in the service layer cannot create a second one —
     * the insert fails instead. This is the constraint the specification asks
     * for, made structural rather than a rule someone has to remember.
     */
    uniqueIndex('uq_fernando_source')
      .on(t.kind, t.sourceId)
      .where(sql`source_id IS NOT NULL AND deleted_at IS NULL`),
    index('idx_fernando_kind').on(t.kind),
    index('idx_fernando_date').on(t.date),
  ],
);

export const inventoryItems = sqliteTable(
  'inventory_items',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    category: text('category').notNull().default(''),
    quantity: integer('quantity').notNull().default(0),
    unitCostCents: integer('unit_cost_cents').notNull().default(0),
    /** Cash actually paid for the lot. The asset's value derives from this. */
    purchaseCostCents: integer('purchase_cost_cents').notNull().default(0),
    purchaseDate: text('purchase_date').notNull(),
    supplier: text('supplier').notNull().default(''),
    notes: text('notes').notNull().default(''),
    ...auditColumns,
  },
  (t) => [index('idx_inventory_name').on(t.name)],
);

export const inventoryUsages = sqliteTable(
  'inventory_usages',
  {
    id: text('id').primaryKey(),
    inventoryItemId: text('inventory_item_id')
      .notNull()
      .references(() => inventoryItems.id),
    vehicleId: text('vehicle_id')
      .notNull()
      .references(() => vehicles.id),
    quantity: integer('quantity').notNull(),
    unitCostCents: integer('unit_cost_cents').notNull(),
    date: text('date').notNull(),
    expenseId: text('expense_id')
      .notNull()
      .references(() => expenses.id),
    createdAt: text('created_at').notNull(),
    deletedAt: text('deleted_at'),
  },
  (t) => [
    index('idx_usage_item').on(t.inventoryItemId),
    index('idx_usage_vehicle').on(t.vehicleId),
  ],
);

/** User-added expense categories, alongside the seeded ones in domain/categories.ts. */
export const customCategories = sqliteTable('custom_categories', {
  id: text('id').primaryKey(),
  label: text('label').notNull(),
  group: text('group_name').notNull().default('OTHER'),
  ...auditColumns,
});

export const photos = sqliteTable(
  'photos',
  {
    id: text('id').primaryKey(),
    vehicleId: text('vehicle_id')
      .notNull()
      .references(() => vehicles.id),
    /** Path relative to the app's document directory — never an absolute path, */
    /** which changes on every iOS app update and would break every image. */
    relativePath: text('relative_path').notNull(),
    caption: text('caption').notNull().default(''),
    isCover: integer('is_cover', { mode: 'boolean' }).notNull().default(false),
    sortOrder: integer('sort_order').notNull().default(0),
    ...auditColumns,
  },
  (t) => [index('idx_photos_vehicle').on(t.vehicleId)],
);

/** Schema version, last-export date, and settings. One row per key. */
export const appMeta = sqliteTable('app_meta', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const schema = {
  vehicles,
  expenses,
  sales,
  capitalEvents,
  distributions,
  fernandoEntries,
  inventoryItems,
  inventoryUsages,
  customCategories,
  photos,
  appMeta,
};
